### ISSUE TITLE
[依頼]ProtoSpace挙動確認

### ISSUE THREAD

**Issue by Takagineer** [Takagineer/protospace-33000#1]
https://protospace-33000.herokuapp.com/

**Comment by Uri-sayaka** [comment]
Takagineerさん、ご提出ありがとうございます！

[修正箇所]
上記投稿頂きましたHerokuのアドレスでアプリケーションエラーが出てしまい、アクセスできない状況でございます。
今一度ご確認お願い致します。

修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/ZdLeprTTWhMA8aZA7
